\documentclass{article}
\usepackage[subfolder, cleanup]{gnuplottex}
\usepackage[nogin]{Sweave}
\begin{document}
\SweaveOpts{concordance=TRUE}

Hola mundo, aqui de nuevo  
<<>>=
#creando funcion con 1 parametro de entrada 
estadistica <- function(x){
  z <- ceiling(length(x)/2)
  tabla <- data.frame(x) 
  tabla[z,"Media"] <- mean(x)
  tabla[z,"DE"] <- sd(x)
  tabla
}
estadistica(a) 
 b <- c(1,2,3)
@


\begin{gnuplot}[terminal=cairolatex]
plot x
\end{gnuplot}
\end{document}
